# Generated by Django 4.2.5 on 2023-09-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tg_chat_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tg_username',
        ),
        migrations.AlterField(
            model_name='student',
            name='github',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
