# Generated by Django 4.2.5 on 2023-09-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_phone_remove_student_tg_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='students.student'),
        ),
    ]
