# Generated by Django 4.2.5 on 2023-09-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='created_at',
        ),
        migrations.AddField(
            model_name='attempt',
            name='last_attempt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
